spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
#    更新数据库表结构
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.176.129
    database: 0
    port: 6379
logging:
  level:
    root: info
    com.yg.blog: debug #指定包中的日志级别
  file: log/blog-dev.log #生产日志文件




